### ISSUE TITLE
Cart Joining

### ISSUE THREAD

**Issue by pollend** [Terasology/Rails#17] opened 2017-10-31 07:04 UTC
In the legacy branch of this repository; It used to be possible to link to carts together and push it as a train. It would be an improvement to add an extension to the solver that allowed carts to be linked and pulled together.

**Comment by eviltak** [comment] 2017-12-05 11:52
Is this a duplicate of #21?

**Comment by jellysnake** [comment] 2017-12-05 14:16
Looks like it yup, good catch. I'll close this one as the other has more information

**Closed by jellysnake** 2017-12-05 14:16 UTC
Labels: Enhancement
