### ISSUE TITLE
Trying to place a loco in multiplayer results in a denial

### ISSUE THREAD

**Issue by Cervator** [Terasology/Rails#40] opened 2018-02-03 19:20 UTC
* Request a loco - `give locoItem`
* Try to place it on some rails
* Get `14:19:17.093 [main] INFO  o.t.logic.characters.CharacterSystem - Denied activation attempt by Cervator861 since at the authority another entity would have been activated`

**Comment by mayant15** [comment] 2019-07-03 23:11
Caused by [this issue](https://github.com/Terasology/AdvancedRails/issues/2)

Placing a loco where another loco should be makes `hitEntity` a loco and `target` a simple rail, which fails [this check](https://github.com/MovingBlocks/Terasology/blob/2faeb11c153383cc38ca38d1ac471ca529bd781a/engine/src/main/java/org/terasology/logic/characters/CharacterSystem.java#L371)

**Comment by mayant15** [comment] 2019-07-06 22:57
Solved in AdvancedRails. Closing this issue.

**Closed by mayant15** 2019-07-06 22:57 UTC
Labels: Bug
